### ISSUE TITLE
Søkeresultatene forsvinner på et tidspunkt

### ISSUE THREAD

**Issue by carsmie** [kartverket/norgeskart3#210]
Test av **melding når det ikke er et søketreff**
Begynner å skrive _Kartverksveien_ og listen med treff vises, 
når en legger til et tall _Kartverksveien 2_, forsvinner listen, 
så skiver en ferdig, _Kartverksveien 21_, da kommer treffet igjen

**Comment by jucir** [comment]
Fixed. Added scope.showSearchResultPanel(); when coordinates.length > 0.
